# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json
gui:
  mainPanelSplitMode: 'vertical'
  sidePanelWidth: 0.15
  splitDiff: 'auto'
  commitHashLength: 0
git:
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never --wrap-max-lines=unlimited --side-by-side --tabs=2
os:
  editPreset: 'vscode'
